name: colapsoload
description: ColapsoLoad — Cliente de escritorio Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP + cookies de sesión
  dio: ^5.4.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1

  # Criptografía (RSA-OAEP + AES-GCM)
  pointycastle: ^3.9.1
  crypto: ^3.0.3

  # Selección y guardado de archivos
  file_picker: ^8.1.2
  path_provider: ^2.1.4

  # Navegación
  go_router: ^14.2.0

  # State management
  provider: ^6.1.2

  # Tipografía
  google_fonts: ^6.2.1

  # Drag & drop de archivos (desktop)
  desktop_drop: ^0.4.4

  # Utilidades
  path: ^1.9.0
  asn1lib: ^1.6.5
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
